apiVersion: v1
kind: Template
metadata:
  name: jenkins-s2i
parameters:
  - description: Git source URI for Jenkins S2I
    name: JENKINS_S2I_URL
    value: https://github.com/coreos/fedora-coreos-pipeline
  - description: Git branch/tag reference for Jenkins S2I
    name: JENKINS_S2I_REF
    value: main
  - name: JENKINS_AGENT_BASE_TAG
    description: Tag name of base OpenShift Jenkins agent image
    value: latest

objects:

  ### JENKINS CONTROLLER ###

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins
    # Note no triggers: we don't want e.g. git pushes/config changes to restart
    # Jenkins. Let's just require manual restarts here. XXX: Should investigate
    # if there's an easy way to auto-redeploy during downtimes.
    spec:
      source:
        type: Git
        git:
          uri: ${JENKINS_S2I_URL}
          ref: ${JENKINS_S2I_REF}
        contextDir: jenkins/controller
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins:2
            namespace: openshift
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins:2
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  ### JENKINS AGENT ###

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-agent
    spec:
      lookupPolicy:
        # this allows e.g. the pipeline to directly reference the imagestream
        local: true
      tags:
        - name: ${JENKINS_AGENT_BASE_TAG}
          from:
            kind: ImageStreamTag
            name: jenkins-agent-base:latest
            namespace: openshift
          referencePolicy:
            type: Source
