# This template is instantiated only if an additional root CA is needed. Note it
# doesn't actually need to be a template (there are no parameters), but the way
# `deploy` currently works expects it as a template.

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-with-cert
labels:
  app: coreos-pipeline
  template: coreos-pipeline-jenkins-with-cert-template
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins-with-cert
    spec:
      source:
        dockerfile: |
          FROM overridden
          COPY cert/data /etc/pki/ca-trust/source/anchors/root-ca.crt
          USER root
          RUN update-ca-trust
          # restore previous user ID
          # https://github.com/openshift/jenkins/blob/7bae76f4412d28c18ed2b33aaf73306734b7f6d5/2/Dockerfile.rhel8#L107
          USER 1001
        secrets:
          - destinationDir: cert
            secret:
              name: additional-root-ca-cert
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins:scheduled-upgrade-redeploy
            namespace: openshift
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins-agent-base-with-cert
    spec:
      source:
        dockerfile: |
          FROM overridden
          COPY cert/data /etc/pki/ca-trust/source/anchors/root-ca.crt
          RUN update-ca-trust
        secrets:
          - destinationDir: cert
            secret:
              name: additional-root-ca-cert
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins-agent-base:scheduled-upgrade
            namespace: openshift
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-agent-base:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
