apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-s2i
labels:
  app: coreos-pipeline
  template: coreos-pipeline-jenkins-s2i-template
parameters:
  - description: Git source URI for Jenkins S2I
    name: JENKINS_S2I_URL
    value: https://github.com/coreos/fedora-coreos-pipeline
  - description: Git branch/tag reference for Jenkins S2I
    name: JENKINS_S2I_REF
    value: main
  - description: Pull spec for Jenkins image
    name: JENKINS_S2I_PULL_SPEC
    value: registry.redhat.io/ocp-tools-4/jenkins-rhel9:v4.17.0
  - description: Pull spec for Jenkins agent image
    name: JENKINS_AGENT_PULL_SPEC
    value: registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel9:v4.17.0

# Here's what the flow looks like when no cert is required:
#
# ┌──────────────────────────────────────────────────────┐   ┌─────────────┐   ┌─────────────┐
# │ Pull spec                                            │   │ buildconfig │   │ imagestream │
# │ registry.redhat.io/ocp-tools-4/jenkins-rhel9:v4.17.0 ├──►│ jenkins-s2i ├──►│ jenkins:2   │
# └──────────────────────────────────────────────────────┘   └─────────────┘   └─────────────┘
#
# ┌─────────────────────────────────────────────────────────────────┐   ┌───────────────────────────┐
# │ Pull spec                                                       │   │ imagestream               │
# │ registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel9:v4.17.0 │──►│ jenkins-agent-base:latest │
# └─────────────────────────────────────────────────────────────────┘   └───────────────────────────┘
#
# And with cert required (see `jenkins-with-cert.yaml`):
#
# ┌───────────────────────────────────────────────────────┐   ┌───────────────────┐   ┌────────────────┐   ┌─────────────┐   ┌─────────────┐
# │ Pull spec                                             │   │ buildconfig       │   │ imagestream    │   │ buildconfig │   │ imagestream │
# │ registry.redhat.io/ocp-tools-4/jenkins--rhel9:v4.17.0 ├──►│ jenkins-with-cert ├──►│ jenkins:latest ├──►│ jenkins-s2i ├──►│ jenkins:2   │
# └───────────────────────────────────────────────────────┘   └───────────────────┘   └────────────────┘   └─────────────┘   └─────────────┘
#
# ┌─────────────────────────────────────────────────────────────────┐   ┌──────────────────────────────┐   ┌───────────────────────────┐
# │ Pull spec                                                       │   │ buildconfig                  │   │ imagestream               │
# │ registry.redhat.io/ocp-tools-4/jenkins-agent-base-rhel9:v4.17.0 ├──►│ jenkins-agent-base-with-cert ├──►│ jenkins-agent-base:latest │
# └─────────────────────────────────────────────────────────────────┘   └──────────────────────────────┘   └───────────────────────────┘

objects:

  ### JENKINS CONTROLLER ###

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins-s2i
    # Note no triggers: we don't want e.g. git pushes/config changes to restart
    # Jenkins. Let's just require manual restarts here. XXX: Should investigate
    # if there's an easy way to auto-redeploy during downtimes.
    spec:
      source:
        type: Git
        git:
          uri: ${JENKINS_S2I_URL}
          ref: ${JENKINS_S2I_REF}
        contextDir: jenkins/controller
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: DockerImage
            name: ${JENKINS_S2I_PULL_SPEC}
          env:
            - name: JENKINS_UC_DOWNLOAD
              value: 'https://archives.jenkins.io'
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins:2
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  ### JENKINS AGENT ###

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-agent-base
    spec:
     lookupPolicy:
      # this allows e.g. the pipeline to directly reference the imagestream
      local: true
     tags:
       - name: latest
         from:
           kind: DockerImage
           name: ${JENKINS_AGENT_PULL_SPEC}
         forcePull: true
