apiVersion: v1
kind: Template
labels:
  app: fedora-coreos
  template: fedora-coreos-jenkins-s2i-template
metadata:
  annotations:
    description: |-
      Jenkins S2I builder for Fedora CoreOS.
    iconClass: icon-jenkins
    openshift.io/display-name: Fedora CoreOS Jenkins S2I
    openshift.io/documentation-url: https://github.com/coreos/fedora-coreos-pipeline
    openshift.io/support-url: https://github.com/coreos/fedora-coreos-pipeline
    openshift.io/provider-display-name: Fedora CoreOS
    tags: fcos,jenkins,fedora
  name: fedora-coreos-jenkins-s2i
parameters:
  - description: Git source URI for Jenkins S2I
    name: JENKINS_S2I_URL
    value: https://github.com/coreos/fedora-coreos-pipeline
  - description: Git branch/tag reference for Jenkins S2I
    name: JENKINS_S2I_REF
    value: main

objects:

  ### JENKINS CONTROLLER ###

  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins
    # Note no triggers: we don't want e.g. git pushes/config changes to restart
    # Jenkins. Let's just require manual restarts here. XXX: Should investigate
    # if there's an easy way to auto-redeploy during downtimes.
    spec:
      source:
        type: Git
        git:
          uri: ${JENKINS_S2I_URL}
          ref: ${JENKINS_S2I_REF}
        contextDir: jenkins/controller
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins:2
            namespace: openshift
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins:2
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2

  ### JENKINS SLAVE ###

  # keep a local copy of the Jenkins slave image so we're not constantly pulling
  # it each time from docker.io
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: jenkins-slave-base-centos7
    spec:
      lookupPolicy:
        # this allows e.g. the pipeline to directly reference the imagestream
        local: true
      tags:
        - name: latest
          from:
            kind: DockerImage
            # target :latest for now
            name: docker.io/openshift/jenkins-slave-base-centos7:latest
          importPolicy:
            scheduled: true
