# This template is instantiated only if an additional root CA is needed. Note it
# doesn't actually need to be a template (there are no parameters), but the way
# `deploy` currently works expects it as a template.

apiVersion: v1
kind: Template
metadata:
  name: jenkins-agent
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: jenkins-agent
    spec:
      source:
        dockerfile: |
          FROM overridden
          COPY cert/data /etc/pki/ca-trust/source/anchors/root-ca.crt
          RUN update-ca-trust
        secrets:
          - destinationDir: cert
            secret:
              name: additional-root-ca-cert
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins-agent-base:latest
            namespace: openshift
          forcePull: true
      output:
        to:
          kind: ImageStreamTag
          name: jenkins-agent:latest
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
