# This pod template is used in the Jenkins pipeline by the Kubernetes plugin. It
# defines the actual coreos-assembler container that will do the work.

apiVersion: v1
metadata:
  name: coreos-assembler
kind: Pod
spec:
  containers:
   - name: jnlp
     image: jenkins-slave-base-centos7:latest
     args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
   - name: coreos-assembler
     image: coreos-assembler:master
     imagePullPolicy: Always
     command: ['/usr/bin/dumb-init']
     args: ['sleep', 'infinity']
     env:
       # `aws` fails to expand ~/.aws otherwise since we have no home
       - name: AWS_CONFIG_FILE
         value: /.aws/config
     volumeMounts:
     - name: data
       mountPath: /srv/
     - name: duffy-key
       mountPath: /var/run/secrets/kubernetes.io/duffy-key
       readOnly: true
     - name: aws-creds
       mountPath: /.aws
       readOnly: true
     securityContext:
       privileged: false
  nodeSelector:
    oci_kvm_hook: allowed
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: coreos-assembler-claim2
  - name: duffy-key
    secret:
      secretName: duffy.key
      optional: true
  - name: aws-creds
    secret:
      secretName: fcos-builds-bot-aws-config
      optional: true
