# This pod template is used in the Jenkins pipeline by the Kubernetes plugin. It
# defines the actual coreos-assembler container that will do the work.

apiVersion: v1
metadata:
  name: coreos-assembler
  labels:
    app: fedora-coreos
kind: Pod
spec:
  # run as `jenkins` so we can do `oc start-build`
  serviceAccountName: jenkins
  containers:
   - name: coreos-assembler
     image: COREOS_ASSEMBLER_IMAGE
     imagePullPolicy: Always
     command: ['/usr/bin/dumb-init']
     args: ['sleep', 'infinity']
     volumeMounts:
     - name: srv
       mountPath: /srv/
     securityContext:
       privileged: false
     resources:
       requests:
         cpu: COREOS_ASSEMBLER_CPU_REQUEST
         memory: COREOS_ASSEMBLER_MEMORY_REQUEST
         devices.kubevirt.io/kvm: '1'
       limits:
         devices.kubevirt.io/kvm: '1'
         cpu: COREOS_ASSEMBLER_CPU_LIMIT
  volumes:
  - name: srv
    emptyDir: {}
