# This pod template is used in the Jenkins pipeline by the Kubernetes plugin. It
# defines the actual coreos-assembler container that will do the work.

apiVersion: v1
metadata:
  name: coreos-assembler
  labels:
    app: fedora-coreos
kind: Pod
spec:
  # run as `jenkins` so we can do `oc start-build`
  serviceAccountName: jenkins
  containers:
   - name: jnlp
     image: jenkins-agent:JENKINS_AGENT_IMAGE_TAG
     args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
   - name: coreos-assembler
     image: COREOS_ASSEMBLER_IMAGE
     imagePullPolicy: Always
     command: ['/usr/bin/dumb-init']
     args: ['sleep', 'infinity']
     env:
       - name: AWS_FCOS_BUILDS_BOT_CONFIG
         value: /.aws-fcos-builds-bot-config/config
       - name: AWS_FCOS_KOLA_BOT_CONFIG
         value: /.aws-fcos-kola-bot-config/config
       # This one doesn't have a config subdirectory
       - name: AZURE_KOLA_TESTS_CONFIG
         value: /.azure-kola-tests-config
       - name: GCP_IMAGE_UPLOAD_CONFIG
         value: /.gcp-image-upload-config/config
       - name: GCP_KOLA_TESTS_CONFIG
         value: /.gcp-kola-tests-config/config
       - name: OPENSTACK_KOLA_TESTS_CONFIG
         value: /.openstack-kola-tests-config/config
     volumeMounts:
     - name: srv
       mountPath: /srv/
     - name: aws-fcos-builds-bot-config
       mountPath: /.aws-fcos-builds-bot-config/
       readOnly: true
     - name: aws-fcos-kola-bot-config
       mountPath: /.aws-fcos-kola-bot-config/
       readOnly: true
     - name: azure-kola-tests-config
       mountPath: /.azure-kola-tests-config/
       readOnly: true
     - name: gcp-image-upload-config
       mountPath: /.gcp-image-upload-config/
       readOnly: true
     - name: gcp-kola-tests-config
       mountPath: /.gcp-kola-tests-config/
       readOnly: true
     - name: openstack-kola-tests-config
       mountPath: /.openstack-kola-tests-config/
       readOnly: true
     - name: fedora-messaging-cfg
       mountPath: /etc/fedora-messaging-cfg
       readOnly: true
     - name: fedora-messaging-coreos-key
       mountPath: /run/kubernetes/secrets/fedora-messaging-coreos-key
       readOnly: true
     securityContext:
       privileged: false
     resources:
       requests:
         cpu: COREOS_ASSEMBLER_CPU_REQUEST
         memory: COREOS_ASSEMBLER_MEMORY_REQUEST
         devices.kubevirt.io/kvm: '1'
       limits:
         devices.kubevirt.io/kvm: '1'
         cpu: COREOS_ASSEMBLER_CPU_LIMIT
  volumes:
  - name: srv
    emptyDir: {}
  # This secret is used for uploading to AWS
  - name: aws-fcos-builds-bot-config
    secret:
      secretName: aws-fcos-builds-bot-config
      optional: true
  # This secret is used for running aws kola tests
  - name: aws-fcos-kola-bot-config
    secret:
      secretName: aws-fcos-kola-bot-config
      optional: true
  # This secret is used for running Azure kola tests
  - name: azure-kola-tests-config
    secret:
      secretName: azure-kola-tests-config
      optional: true
  # This secret is used for uploading to GCP
  - name: gcp-image-upload-config
    secret:
      secretName: gcp-image-upload-config
      optional: true
  # This secret is used for running GCP kola tests
  - name: gcp-kola-tests-config
    secret:
      secretName: gcp-kola-tests-config
      optional: true
  # This secret is used for running OpenStack kola tests
  - name: openstack-kola-tests-config
    secret:
      secretName: openstack-kola-tests-config
      optional: true
  # These two here are used for signing with RoboSignatory
  - name: fedora-messaging-cfg
    configMap:
      name: fedora-messaging-cfg
      optional: true
  - name: fedora-messaging-coreos-key
    secret:
      secretName: fedora-messaging-coreos-key
      optional: true
