# A container to just get into the coreos-assembler environment
# (container + mounted physical volume under /srv/)
apiVersion: v1
metadata:
    name: coreos-assembler-sleep
kind: Pod
spec:
  containers:
   - name: coreos-assembler-sleep
     image: docker-registry.default.svc:5000/fedora-coreos/coreos-assembler:master
#    image: quay.io/coreos-assembler/coreos-assembler:master
     imagePullPolicy: Always
     workingDir: /srv/
     command: ['/bin/bash']
     args: ['-c', 'sleep infinity']
     volumeMounts:
     - name: data
       mountPath: /srv/
     - name: duffy-key
       mountPath: /var/run/secrets/kubernetes.io/duffy-key
       readOnly: true
     securityContext:
       privileged: false
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: coreos-assembler-claim
  - name: duffy-key
    secret:
      secretName: duffy.key
