# A container to just get into the coreos-assembler environment.
apiVersion: v1
metadata:
    name: coreos-assembler-sleep
kind: Pod
spec:
  containers:
   - name: coreos-assembler-sleep
     image: quay.io/coreos-assembler/coreos-assembler:main
     imagePullPolicy: Always
     workingDir: /srv/
     command: ['/usr/bin/dumb-init']
     args: ['sleep', 'infinity']
     volumeMounts:
     - name: srv
       mountPath: /srv/
     securityContext:
       privileged: false
     resources:
       requests:
         devices.kubevirt.io/kvm: '1'
       limits:
         devices.kubevirt.io/kvm: '1'
  volumes:
  - name: srv
    emptyDir: {}
