# A container to just get into the coreos-assembler environment.
apiVersion: v1
metadata:
    name: coreos-assembler-sleep
kind: Pod
spec:
  containers:
   - name: coreos-assembler-sleep
     image: coreos-assembler:main
     imagePullPolicy: Always
     workingDir: /srv/
     command: ['/usr/bin/dumb-init']
     args: ['sleep', 'infinity']
     securityContext:
       privileged: false
