# A container to just get into the coreos-assembler environment
# (container + mounted physical volume under /srv/)
apiVersion: v1
metadata:
    name: coreos-assembler-sleep
kind: Pod
spec:
  containers:
   - name: coreos-assembler-sleep
     image: coreos-assembler:master
     imagePullPolicy: Always
     workingDir: /srv/
     command: ['/usr/bin/dumb-init']
     args: ['sleep', 'infinity']
     volumeMounts:
     - name: data
       mountPath: /srv/
     - name: duffy-key
       mountPath: /var/run/secrets/kubernetes.io/duffy-key
       readOnly: true
     securityContext:
       privileged: false
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: coreos-assembler-claim2
  - name: duffy-key
    secret:
      secretName: duffy.key
      optional: true
