#!/usr/bin/python3

import json
import os
import sys

def set_enabled(enabled):
    dir = os.path.realpath(os.path.dirname(sys.argv[0]))
    def write_json(filename, contents):
        with open(os.path.join(dir, filename), 'w') as fh:
            json.dump(contents, fh, indent=4)
            fh.write("\n")

    # fields for FCOS infrastructure
    write_json('status.json', {
        'enabled': enabled,
    })
    # fields for shields.io endpoint
    write_json('badge.json', {
        'schemaVersion': 1,
        'style': 'for-the-badge',
        'label': os.path.basename(dir),
        'message': 'open' if enabled else 'closed',
        'color': 'green' if enabled else 'lightgrey',
    })
    # Groovy for pipeline
    with open(os.path.join(dir, 'status.groovy'), 'w') as fh:
        fh.write('// Automatically generated by manage.py; do not edit\n\n' +
                f'''streams = [{"'next-devel'" if enabled else ""}]\n''')


if __name__ == '__main__':
    try:
        if sys.argv[1] == 'enable':
            set_enabled(True)
        elif sys.argv[1] == 'disable':
            set_enabled(False)
        else:
            raise IndexError
    except IndexError:
        print(f'Usage: {sys.argv[0]} {{enable|disable}}')
