credentials:
  system:
    domainCredentials:
      - credentials:
        - aws:
            scope: GLOBAL
            id: aws-build-upload-config
            accessKey: ${aws-build-upload-config/accessKey}
            secretKey: ${aws-build-upload-config/secretKey}
            description: AWS build upload credentials
