credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: coreos-s390x-builder-host-string
            secret: ${coreos-s390x-builder/host}
            description: coreos s390x Builder Host
        - string:
            scope: GLOBAL
            id: coreos-s390x-builder-user-string
            secret: ${coreos-s390x-builder/user}
            description: coreos s390x Builder User
        - string:
            scope: GLOBAL
            id: coreos-s390x-builder-uid-string
            secret: ${coreos-s390x-builder/uid}
            description: coreos s390x Builder UID
        - basicSSHUserPrivateKey:
            scope: GLOBAL
            id: coreos-s390x-builder-sshkey-key
            username: builder
            description: coreos s390x Builder SSH Key
            privateKeySource:
              directEntry:
                privateKey: "${readFile:${coreos-s390x-builder/sshkey}}"
