credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: fcos-aarch64-builder-host-string
            secret: ${fcos-aarch64-builder/host}
            description: FCOS AARCH64 Builder Host
        - string:
            scope: GLOBAL
            id: fcos-aarch64-builder-user-string
            secret: ${fcos-aarch64-builder/user}
            description: FCOS AARCH64 Builder User
        - string:
            scope: GLOBAL
            id: fcos-aarch64-builder-uid-string
            secret: ${fcos-aarch64-builder/uid}
            description: FCOS AARCH64 Builder UID
        - basicSSHUserPrivateKey:
            scope: GLOBAL
            id: fcos-aarch64-builder-sshkey-key
            username: builder
            description: FCOS AARCH64 Builder SSH Key
            privateKeySource:
              directEntry:
                privateKey: "${readFile:${fcos-aarch64-builder/sshkey}}"
