credentials:
  system:
    domainCredentials:
      - credentials:
        - string:
            scope: GLOBAL
            id: github-webhook-shared-secret
            secret: ${github-webhook-shared-secret/secret}
            description: GitHub Webhook Shared Secret
unclassified:
  gitHubPluginConfig:
    hookSecretConfigs:
      - credentialsId: github-webhook-shared-secret
    configs:
      - credentialsId: github-coreosbot-token-string
        manageHooks: true
