credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: github-coreosbot-token
            username: coreosbot
            password: ${github-coreosbot-token/token}
            description: GitHub coreosbot token
        - string:
            scope: GLOBAL
            id: github-coreosbot-token-string
            secret: ${github-coreosbot-token/token}
            description: GitHub coreosbot token as a string
