credentials:
  system:
    domainCredentials:
      - credentials:
        - file:
            scope: GLOBAL
            fileName: oscontainer-secret
            id: oscontainer-secret
            # See: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc#passing-secrets-through-variables
            secretBytes: "${base64:${readFile:${oscontainer-secret/dockerconfig}}}"
            description: Push secret for quay.io/coreos-assembler/fcos

