# This seed job simply defines a new pipeline job for each Jenkinsfile found in
# the jobs/ directory of the target jenkins jobs repo.

security:
  globalJobDslSecurityConfiguration:
    # turn off approval for job DSL; we already approve scripts via PR review
    useScriptSecurity: false
jobs:
  - script: |
      pipelineJob('seed') {
        definition {
          cps {
            sandbox(true)
            script('''
              properties([
                parameters([
                  booleanParam(name: 'FORCE',
                               defaultValue: false,
                               description: 'Whether to redefine existing jobs (make sure to rerun all jobs with triggers to re-activate them)'),
                ]),
                buildDiscarder(logRotator(
                    numToKeepStr: '100',
                    artifactNumToKeepStr: '100'
                )),
                durabilityHint('PERFORMANCE_OPTIMIZED')
              ])

              node {
                // XXX: hack, should put this in coreos-ci-lib
                sh("curl -LO https://raw.githubusercontent.com/coreos/fedora-coreos-pipeline/main/utils.groovy")
                def pipeutils = load("utils.groovy")
                def jenkinscfg = pipeutils.load_jenkins_config()
                def url = jenkinscfg["jenkins-jobs-url"]
                def ref = jenkinscfg["jenkins-jobs-ref"]
                shwrap("rm -rf source")
                shwrap("git clone -b ^${ref} ^${url} source")

                findFiles(glob: "source/jobs/*.Jenkinsfile").each { file ->
                  def split = file.name.split("\\\\.")
                  assert split[1] == "Jenkinsfile"
                  def jobName = split[0]
                  jobDsl ignoreExisting: !params.FORCE, scriptText: """
                    pipelineJob("^${jobName}") {
                      definition {
                        cpsScm {
                          scm {
                            git {
                              remote { url("^${url}") }
                              branches("^${ref}")
                              extensions { }
                            }
                            scriptPath("jobs/^${file.name}")
                          }
                        }
                      }
                    }
                  """
                }
              }
            '''.stripIndent())
          }
        }
      }
      queue('seed')
